# Generated by Django 4.0.3 on 2022-04-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='user_action',
            field=models.IntegerField(default=0),
        ),
    ]
