# Generated by Django 4.0.3 on 2022-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_alter_useraction_user_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('order_step', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
