# Generated by Django 4.0.3 on 2022-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_simorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
